In [2]:
import pandas as pd
import numpy as np

In [ ]:
# load data1
data1 = pd.read_csv('data1.csv')

data1

In [ ]:
# Convert text to uppercase in column: 'Current school (or last school attended)'
data1['Current school (or last school attended)'] = data1['Current school (or last school attended)'].str.upper()
# save data1
data1.to_csv('data1.csv', index=False)

data1

,City,How would you describe your current situation? Please check ALL that apply.,Current school (or last school attended),Academic Year,On what device(s) will you use DataCamp?,Are you currently receiving any other forms of financial assistance or scholarships?,"On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?",How much time will you dedicate to use DataCamp regularly?,"After using DataCamp for 6-12 months, are you willing and able to fill out and submit this survey about your experience?"
0,Reghaia,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,3-5 hours/week,Yes
1,Chlef,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,1-2 hours/week,Yes
2,Algiers,Unemployed,ESI,1CS / L3,My own computer,No,1,3-5 hours/week,Yes
3,Annaba,Student aged 16-26,ESI,1CS / L3,My own mobile iOS/Android device,No,2,3-5 hours/week,Yes
4,Algiers,Student aged 16-26,USTHB,1CS / L3,My own computer,No,2,3-5 hours/week,Yes
...,...,...,...,...,...,...,...,...,...
142,Algiers,Unemployed,ESI,2CS / M1,My own computer,No,2,1-2 hours/week,Yes
143,Algiers,Student aged 16-26,ESI,2CS / M1,My own mobile iOS/Android device,No,3,3-5 hours/week,Yes
144,Algiers,Student aged 16-26,USTHB,2CP / L2,My own computer,No,1,1-2 hours/week,Maybe
145,Algiers,Student aged 16-26,ESI,1CS / L3,My own mobile iOS/Android device,No,2,1-2 hours/week,Yes
146,Algiers,Student aged 16-26,ESI,3CS / M2,My own computer,No,4,3-5 hours/week,Yes

In [ ]:
# add IDs to the data1

data1['ID'] = np.arange(1, len(data1) + 1)

data1.to_csv('data1.csv', index=False)

In [ ]:
# put the ID column in the first position
cols = data1.columns.tolist()
cols = cols[-1:] + cols[:-1]
data1 = data1[cols]

#save data1
data1.to_csv('data1.csv', index=False)

data1

,ID,City,How would you describe your current situation? Please check ALL that apply.,Current school (or last school attended),Academic Year,On what device(s) will you use DataCamp?,Are you currently receiving any other forms of financial assistance or scholarships?,"On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?",How much time will you dedicate to use DataCamp regularly?,"After using DataCamp for 6-12 months, are you willing and able to fill out and submit this survey about your experience?"
0,1,Reghaia,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,3-5 hours/week,Yes
1,2,Chlef,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,1-2 hours/week,Yes
2,3,Algiers,Unemployed,ESI,1CS / L3,My own computer,No,1,3-5 hours/week,Yes
3,4,Annaba,Student aged 16-26,ESI,1CS / L3,My own mobile iOS/Android device,No,2,3-5 hours/week,Yes
4,5,Algiers,Student aged 16-26,USTHB,1CS / L3,My own computer,No,2,3-5 hours/week,Yes
...,...,...,...,...,...,...,...,...,...,...
142,143,Algiers,Unemployed,ESI,2CS / M1,My own computer,No,2,1-2 hours/week,Yes
143,144,Algiers,Student aged 16-26,ESI,2CS / M1,My own mobile iOS/Android device,No,3,3-5 hours/week,Yes
144,145,Algiers,Student aged 16-26,USTHB,2CP / L2,My own computer,No,1,1-2 hours/week,Maybe
145,146,Algiers,Student aged 16-26,ESI,1CS / L3,My own mobile iOS/Android device,No,2,1-2 hours/week,Yes
146,147,Algiers,Student aged 16-26,ESI,3CS / M2,My own computer,No,4,3-5 hours/week,Yes

In [ ]:
# capitalize City, turn every alger into algiers in that column
# in On what device(s) will you use DataCamp?, turn every My own mobile iOS/Android device into My own mobile device

data1['City'] = data1['City'].str.capitalize()
data1['City'] = data1['City'].replace('Alger', 'Algiers')

data1['On what device(s) will you use DataCamp?'] = data1['On what device(s) will you use DataCamp?'].replace('My own mobile iOS/Android device', 'My own mobile device')

# save data1
data1.to_csv('data1.csv', index=False)

data1

,ID,City,How would you describe your current situation? Please check ALL that apply.,Current school (or last school attended),Academic Year,On what device(s) will you use DataCamp?,Are you currently receiving any other forms of financial assistance or scholarships?,"On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?",How much time will you dedicate to use DataCamp regularly?,"After using DataCamp for 6-12 months, are you willing and able to fill out and submit this survey about your experience?"
0,1,Reghaia,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,3-5 hours/week,Yes
1,2,Chlef,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,1-2 hours/week,Yes
2,3,Algiers,Unemployed,ESI,1CS / L3,My own computer,No,1,3-5 hours/week,Yes
3,4,Annaba,Student aged 16-26,ESI,1CS / L3,My own mobile device,No,2,3-5 hours/week,Yes
4,5,Algiers,Student aged 16-26,USTHB,1CS / L3,My own computer,No,2,3-5 hours/week,Yes
...,...,...,...,...,...,...,...,...,...,...
142,143,Algiers,Unemployed,ESI,2CS / M1,My own computer,No,2,1-2 hours/week,Yes
143,144,Algiers,Student aged 16-26,ESI,2CS / M1,My own mobile device,No,3,3-5 hours/week,Yes
144,145,Algiers,Student aged 16-26,USTHB,2CP / L2,My own computer,No,1,1-2 hours/week,Maybe
145,146,Algiers,Student aged 16-26,ESI,1CS / L3,My own mobile device,No,2,1-2 hours/week,Yes
146,147,Algiers,Student aged 16-26,ESI,3CS / M2,My own computer,No,4,3-5 hours/week,Yes

In [ ]:
# one hot encode every column except the ID column
data1 = pd.get_dummies(data1, columns=data1.columns[1:-1])

data1.to_csv('data_encoded.csv', index=False)

In [ ]:
# get the different values in all columns
for col in data1.columns[1:]:
    print(col)
    print(data1[col].unique())

In [ ]:
# count the number of unique values in each column
data1.nunique()

# get count of each value in all columns
for col in data1.columns[1:]:
    print(data1[col].value_counts())

City
Algiers           87
Boumerdes          9
Medea              9
Blida              7
Tlemcen            4
Tizi               3
Chlef              3
Constantine        2
Tipaza             2
Setif              2
Algeirs            2
Adrar              2
Algiers            1
Bejaia             1
Bousaada           1
Ouargla            1
Batna              1
Reghaia            1
Oran               1
Alger              1
Bouira             1
Ghardaia           1
Tissemssilt        1
Msila              1
Oum el bouagui     1
Annaba             1
Khenchela          1
Name: count, dtype: int64
How would you describe your current situation? Please check ALL that apply.
Student aged 16-26              110
Unemployed                       34
Nonprofit research scientist      3
Name: count, dtype: int64
Current school (or last school attended)
ESI                         87
USTHB                       21
UNIVERSITY ALGIERS 1         7
ESI                          6
HIS                          6
ESTIN                        5
ESB                          3
ENP                          2
UMBB                         2
INELEC                       2
ENSIA                        1
SAAD DAHLAB UNIVERSITY       1
ENSSEA                       1
UNIVERSITY CONSTANTINE 2     1
ESI SBA                      1
USTHB                        1
Name: count, dtype: int64
Academic Year
1CS / L3             47
2CS / M1             33
1CP / L1             31
2CP / L2             30
Graduate / Alumni     3
3CS / M2              3
Name: count, dtype: int64
On what device(s) will you use DataCamp?
My own computer         103
My own mobile device     44
Name: count, dtype: int64
Are you currently receiving any other forms of financial assistance or scholarships?
No     145
Yes      2
Name: count, dtype: int64
On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?
2    57
1    51
3    30
4     8
5     1
Name: count, dtype: int64
How much time will you dedicate to use DataCamp regularly?
3-5 hours/week    79
>5 hours/week     48
1-2 hours/week    20
Name: count, dtype: int64
After using DataCamp for 6-12 months, are you willing and able to fill out and submit this survey about your experience?
Yes      119
Maybe     27
No         1
Name: count, dtype: int64

In [30]:
# in City, turn every alger into algiers in that column, turn every algeirs into algiers in that column, turn every bouira into algiers, turn every bejaia into tizi, 

data['City'] = data['City'].replace('Alger', 'Algiers')
data['City'] = data['City'].replace('Algeirs', 'Algiers')
data['City'] = data['City'].replace('Bouira', 'Algiers')
data['City'] = data['City'].replace('Bejaia', 'Tizi')

# save data
data.to_csv('data.csv', index=False)

data

,ID,City,How would you describe your current situation? Please check ALL that apply.,Current school (or last school attended),Academic Year,On what device(s) will you use DataCamp?,Are you currently receiving any other forms of financial assistance or scholarships?,"On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?",How much time will you dedicate to use DataCamp regularly?,"After using DataCamp for 6-12 months, are you willing and able to fill out and submit this survey about your experience?"
0,1,Reghaia,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,3-5 hours/week,Yes
1,2,Chlef,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,1-2 hours/week,Yes
2,3,Algiers,Unemployed,ESI,1CS / L3,My own computer,No,1,3-5 hours/week,Yes
3,4,Annaba,Student aged 16-26,ESI,1CS / L3,My own mobile device,No,2,3-5 hours/week,Yes
4,5,Algiers,Student aged 16-26,USTHB,1CS / L3,My own computer,No,2,3-5 hours/week,Yes
...,...,...,...,...,...,...,...,...,...,...
142,143,Algiers,Unemployed,ESI,2CS / M1,My own computer,No,2,1-2 hours/week,Yes
143,144,Algiers,Student aged 16-26,ESI,2CS / M1,My own mobile device,No,3,3-5 hours/week,Yes
144,145,Algiers,Student aged 16-26,USTHB,2CP / L2,My own computer,No,1,1-2 hours/week,Maybe
145,146,Algiers,Student aged 16-26,ESI,1CS / L3,My own mobile device,No,2,1-2 hours/week,Yes
146,147,Algiers,Student aged 16-26,ESI,3CS / M2,My own computer,No,4,3-5 hours/week,Yes

In [7]:
# count the number of unique values in each column
data = pd.read_csv('data.csv')

data.nunique()

# get count of each value in all columns
for col in data.columns[1:]:
    print(data[col].value_counts())

City
Algiers           93
Boumerdes         10
Medea              9
Blida              8
Chlef              4
Tizi               4
Tlemcen            4
Oran               2
Constantine        2
Tipaza             2
Setif              2
Adrar              2
Annaba             1
Oum el bouagui     1
Batna              1
Ouargla            1
Bousaada           1
Name: count, dtype: int64
How would you describe your current situation?
Student aged 16-26              110
Unemployed                       34
Nonprofit research scientist      3
Name: count, dtype: int64
Current school
ESI                     89
USTHB                   22
UNIVERSITY ALGIERS 1     8
ESI                      6
HIS                      6
ESTIN                    5
ESB                      4
ENP                      2
UMBB                     2
INELEC                   2
ENSIA                    1
Name: count, dtype: int64
Academic Year
1CS / L3             47
2CS / M1             33
1CP / L1             31
2CP / L2             30
Graduate / Alumni     3
3CS / M2              3
Name: count, dtype: int64
On what device will you use DataCamp?
My own computer         103
My own mobile device     44
Name: count, dtype: int64
Are you currently receiving any other forms of financial assistance or scholarships?
No     145
Yes      2
Name: count, dtype: int64
On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?
2    57
1    51
3    30
4     8
5     1
Name: count, dtype: int64
How much time will you dedicate to use DataCamp regularly?
3-5 hours/week    79
>5 hours/week     48
1-2 hours/week    20
Name: count, dtype: int64
After using DataCamp for 6-12 months, are you willing and able to fill out and submit this survey about your experience?
Yes      119
Maybe     27
No         1
Name: count, dtype: int64

In [57]:
# one hot encode data_encoded , except the ID and city column
data_encoded = pd.get_dummies(data, columns=data.columns[2:])

#save data_encoded

data_encoded.to_csv('data_encoded.csv', index=False)

In [8]:
# convert the cells of this column : "On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?" to strings
data['On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?'] = data['On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?'].astype(str)

# save data
data.to_csv('data.csv', index=False)

data

,ID,City,How would you describe your current situation?,Current school,Academic Year,On what device will you use DataCamp?,Are you currently receiving any other forms of financial assistance or scholarships?,"On a scale of 1-5, how much do you know about data science, analysis, engineering, AI, and/or machine learning?",How much time will you dedicate to use DataCamp regularly?,"After using DataCamp for 6-12 months, are you willing and able to fill out and submit this survey about your experience?"
0,1,Algiers,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,3-5 hours/week,Yes
1,2,Chlef,Student aged 16-26,ESI,1CP / L1,My own computer,No,1,1-2 hours/week,Yes
2,3,Algiers,Unemployed,ESI,1CS / L3,My own computer,No,1,3-5 hours/week,Yes
3,4,Annaba,Student aged 16-26,ESI,1CS / L3,My own mobile device,No,2,3-5 hours/week,Yes
4,5,Algiers,Student aged 16-26,USTHB,1CS / L3,My own computer,No,2,3-5 hours/week,Yes
...,...,...,...,...,...,...,...,...,...,...
142,143,Algiers,Unemployed,ESI,2CS / M1,My own computer,No,2,1-2 hours/week,Yes
143,144,Algiers,Student aged 16-26,ESI,2CS / M1,My own mobile device,No,3,3-5 hours/week,Yes
144,145,Algiers,Student aged 16-26,USTHB,2CP / L2,My own computer,No,1,1-2 hours/week,Maybe
145,146,Algiers,Student aged 16-26,ESI,1CS / L3,My own mobile device,No,2,1-2 hours/week,Yes
146,147,Algiers,Student aged 16-26,ESI,3CS / M2,My own computer,No,4,3-5 hours/week,Yes